name: payu
channels:
  - accessnri
  - coecms
  - conda-forge
dependencies:
  - python==3.10
  - accessnri::payu==1.2.0
  - f90nml
  - gh
  - git
  - nco
  - pytest
  - openssh==10.0p1
  - openssl==3.5.2
  - xarray
  - mule
  - um2nc
  - accessnri::yamanifest
  - netcdf4=*=nompi_*
  - experiment-generator
  - experiment-runner
  - mnctools
