name: Deploy conda env
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy environment
    runs-on: ubuntu-latest
    environment: Gadi
    steps:
      - name: Setup SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: ${{ secrets.HOST }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy environment
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'

          export SCRIPT_DIR=${{ secrets.REPO_PATH }}/scripts
          export CONDA_ENVIRONMENT=${{ inputs.environment }}

          source $SCRIPT_DIR/install_config.sh

          "${SCRIPT_DIR}"/deploy.sh

          EOT