name: Test conda env
on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  test:
    name: Test environment
    runs-on: ubuntu-latest
    steps:
      - name: Test environment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          script: |
            export SCRIPT_DIR=${{secrets.GADI_REPO_PATH}}/scripts
            eval $( grep ADMIN_DIR $SCRIPT_DIR/install_config.sh )
            eval $( grep JOB_LOG_DIR $SCRIPT_DIR/install_config.sh )
            cd $JOB_LOG_DIR
            # TODO: Update storage flags?
            qsub -N test_${{ inputs.environment }} -lncpus=4,mem=20GB,walltime=0:20:00,jobfs=50GB,storage=scratch/tm70 -v SCRIPT_DIR,CONDA_ENVIRONMENT=${{ inputs.environment }} -P tm70 -Wblock=true -Wumask=037 "${SCRIPT_DIR}"/test.sh